### ISSUE TITLE
Define properties via ActiveModel::Attributes

### ISSUE THREAD

**Issue by phoet** [klausmeyer/fritzbox-smarthome#51]
I was playing around with this gem for some home automation and it would be helpful for discoverability and ease of use to define the attributes in the Actor via `ActiveModel::Attributes` so that `.attributes` `.to_h` etc can be easily supported.

**Comment by klausmeyer** [comment]
Hi @phoet,

thanks for the suggestion. I did play around with it and if you want you can give it a try:

```ruby
gem 'fritzbox-smarthome', '~> 0.8.0', github: 'klausmeyer/fritzbox-smarthome', branch: 'feat/am-attributes'
```

**Comment by phoet** [comment]
nice, looks good, will try it soonish

**Comment by klausmeyer** [comment]
@phoet friendly reminder ;)

**Comment by phoet** [comment]
ups, sorry. checked it out, works like a charm.

```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'fritzbox-smarthome', '~> 0.8.0', github: 'klausmeyer/fritzbox-smarthome', branch: 'feat/am-attributes'
end

require 'fritzbox/smarthome'

ain = ARGV[0]
abort("AIN is required") if ain.nil?

Fritzbox::Smarthome.configure do |config|
  config.endpoint   = 'http://fritz.box'
  config.username   = 'evcc'
  config.password   = 'XXX'
  config.verify_ssl = false
end

actor = Fritzbox::Smarthome::Actor.find_by!(ain: ain)
puts actor.attributes
```

**Comment by klausmeyer** [comment]
Nice. Thanks for verifying.

I will publish a new version soon.

**Comment by klausmeyer** [comment]
Here we go:

https://rubygems.org/gems/fritzbox-smarthome/versions/0.8.0
